/**
 * JobHunter API
 * An ECommerce API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Address { 
    number?: number | null;
    street?: string | null;
    city?: string | null;
    region?: string | null;
}

