/**
 * JobHunter API
 * An ECommerce API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductRM { 
    title?: string | null;
    price?: number;
    description?: string | null;
    quantity?: number;
    category?: string | null;
    comments?: string | null;
}

